// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostInfrastructure;

#nullable disable

namespace PostInfrastructure.Migrations
{
    [DbContext(typeof(PostDbContext))]
    [Migration("20250224090224_topicGenerate")]
    partial class topicGenerate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PostCore.Entities.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Comment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4752c4fe-1546-4c01-a46f-e9fcab755389",
                            AccountName = "tienminh",
                            Content = "Test Du lieu Comment xiu di ban oi",
                            CreatedAt = new DateTime(2025, 2, 24, 16, 2, 23, 612, DateTimeKind.Local).AddTicks(5714),
                            ParentId = "4aa068ad-f48a-42c0-ad99-de7b5e8ad15b",
                            UpdatedAt = new DateTime(2025, 2, 24, 16, 2, 23, 612, DateTimeKind.Local).AddTicks(6053)
                        });
                });

            modelBuilder.Entity("PostCore.Entities.Media", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("MediaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Media", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4758c4fe-1546-4c01-a46f-e9fcab755389",
                            Height = 0.0,
                            MediaName = "testdulieu",
                            MediaType = 0,
                            ParentId = "4aa068ad-f48a-42c0-ad99-de7b5e8ad15b",
                            Url = "/test",
                            Width = 0.0
                        });
                });

            modelBuilder.Entity("PostCore.Entities.Posts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Privacy")
                        .HasColumnType("int");

                    b.Property<string>("RepostId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4aa068ad-f48a-42c0-ad99-de7b5e8ad15b",
                            AccountName = "thienzn",
                            Content = "Test Du lieu xiu di ban oi",
                            CreatedAt = new DateTime(2025, 2, 24, 16, 2, 23, 610, DateTimeKind.Local).AddTicks(8120),
                            Privacy = 1,
                            UpdatedAt = new DateTime(2025, 2, 24, 16, 2, 23, 610, DateTimeKind.Local).AddTicks(8695)
                        });
                });

            modelBuilder.Entity("PostCore.Entities.Reaction", b =>
                {
                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostIdOrCommentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccountName", "PostIdOrCommentId");

                    b.ToTable("Reaction", (string)null);
                });

            modelBuilder.Entity("PostCore.Entities.Topic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CountTopic")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topic", (string)null);
                });

            modelBuilder.Entity("PostCore.Entities.TopicPost", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TopicId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("TopicPost", (string)null);
                });

            modelBuilder.Entity("PostCore.Entities.TopicUser", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TopicId", "UserId");

                    b.ToTable("TopicUser", (string)null);
                });

            modelBuilder.Entity("PostCore.Entities.UserPostViews", b =>
                {
                    b.Property<string>("PostId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("PostId", "UserId");

                    b.ToTable("UserPostViews", (string)null);
                });

            modelBuilder.Entity("PostCore.Entities.TopicPost", b =>
                {
                    b.HasOne("PostCore.Entities.Posts", "Posts")
                        .WithMany("TopicPosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostCore.Entities.Topic", "Topic")
                        .WithMany("TopicPosts")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posts");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("PostCore.Entities.TopicUser", b =>
                {
                    b.HasOne("PostCore.Entities.Topic", "Topic")
                        .WithMany("TopicUsers")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("PostCore.Entities.UserPostViews", b =>
                {
                    b.HasOne("PostCore.Entities.Posts", "Posts")
                        .WithMany("UserPostViews")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("PostCore.Entities.Posts", b =>
                {
                    b.Navigation("TopicPosts");

                    b.Navigation("UserPostViews");
                });

            modelBuilder.Entity("PostCore.Entities.Topic", b =>
                {
                    b.Navigation("TopicPosts");

                    b.Navigation("TopicUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
